.gitignore, README.md, pdf2zh/converter.py, pdf2zh/translator.py
- [feat (translator, convertor): add support for DeepLX](https://github.com/Byaidu/PDFMathTranslate/commit/a0d87c73aa0b1d00c7dabf74c0062d0ef2a9bf98)
- [feat (translator): allow custom API endpoint](https://github.com/Byaidu/PDFMathTranslate/commit/a4227ba1b4c4895f2d1b884c0496679dda41fd41)
- [doc (README): add tutorials for using DeepLX](https://github.com/Byaidu/PDFMathTranslate/commit/128028859958536dbd4277577f151edd410615b8)
=> feat: add supports for DeepLX

pdf2zh/pdf2zh.py
- Moved imports of `doclayout_yolo` and `pdf2zh.high_level` into functions where they are needed, speeding up execution for commands like `--help`.
- Verify the existence of input files before processing.
=> chore: make -v and --help faster

README.md, pdf2zh/converter.py, pdf2zh/translator.py, setup.py
This PR introduces support for Azure Text Translation.
=> feat: support Azure translation

pdf2zh/high_level.py
=> fix: wrong color space conversion

pdf2zh/translator.py
添加腾讯机器翻译接口，读取环境变量中的Tencent_SECRET_ID和Tencent_SECRET_KEY。
暂未解决的问题：
机器翻译接口对于请求的频率有限制，没对高频请求的情况进行解决。
=> 添加腾讯机器翻译接口

pdf2zh/doclayout.py, pdf2zh/high_level.py, pdf2zh/pdf2zh.py, pdf2zh/utils.py, pyproject.toml
Experimental ONNX Support. 
Close #85.
**TODO:**
=> feat: onnx support

pyproject.toml, tools/backend.py, tools/tasks.py
add a simple backend using flask and celery
=> add a simple backend

README.md, README_zh-CN.md
添加--share的说明。
https://github.com/Byaidu/PDFMathTranslate/issues/221
=> 更新readme，添加--share说明。

pdf2zh/gui.py, pdf2zh/high_level.py
Related: #167
Added cancel support for the GUI during translation.
=> Add cancel support for gui

pdf2zh/translator.py
https://github.com/Byaidu/PDFMathTranslate/issues/241
=> openai api状态判断。

README.md, README_ja-JP.md, README_zh-CN.md, pdf2zh/converter.py, pdf2zh/high_level.py, pdf2zh/pdf2zh.py, pdf2zh/pdfinterp.py, pdf2zh/translator.py
cli的自定义prompt完成，ollama自部署环境下测试可用。
https://github.com/Byaidu/PDFMathTranslate/issues/260
=> 添加cli的自定义prompt支持。更新readme

pdf2zh/gui.py
Fix an issue where translation would fail if the threads value was not provided.
=> Fix an issue where translation would fail if the threads value was not provided.

pdf2zh/gui.py
mentioned in https://github.com/Byaidu/PDFMathTranslate/issues/290
=> feat (gui) : pdf preview in high resolution

docs/README_ja-JP.md, docs/README_zh-CN.md
https://github.com/Byaidu/PDFMathTranslate/issues/355
=> 修复非主要readme文档图裂

README.md, docs/ADVANCED.md, docs/APIS.md, docs/README_ja-JP.md, docs/README_zh-CN.md, pdf2zh/backend.py, pdf2zh/converter.py, pdf2zh/doclayout.py, pdf2zh/gui.py, pdf2zh/high_level.py, pdf2zh/pdf2zh.py, pdf2zh/translator.py, pyproject.toml
添加cli的 `--onnx`选项 https://github.com/Byaidu/PDFMathTranslate/issues/300
添加对argos translate支持的translator https://github.com/Byaidu/PDFMathTranslate/issues/318
=> feat (main) : add cli option and argostranslator

docs/ADVANCED.md, docs/README_ja-JP.md, docs/README_zh-CN.md, pdf2zh/converter.py, pdf2zh/gui.py, pdf2zh/high_level.py, pdf2zh/translator.py, test/test_translator.py
https://github.com/Byaidu/PDFMathTranslate/issues/353
https://github.com/Byaidu/PDFMathTranslate/issues/347
修复了https://github.com/Byaidu/PDFMathTranslate/blob/b7b7e5087a0717d7794bda66d4e26ecdf4866d56/pdf2zh/high_level.py#L105 get的值是空的问题。
=> feat (translator) : add new translator and fix bug.

pdf2zh/backend.py, pdf2zh/doclayout.py, pdf2zh/gui.py, pdf2zh/pdf2zh.py
https://github.com/Byaidu/PDFMathTranslate/issues/385
=> fix: Circular import `model`

.github/workflows/python-build.yml
=> cache action pip install

README.md, docs/README_ja-JP.md, docs/README_zh-CN.md, docs/README_zh-TW.md
新增繁體中文的Readme.md，為後續提供英文轉繁中打下基礎
=> feat: add Traditional Chinese language option to README

pdf2zh/converter.py, pdf2zh/gui.py, pdf2zh/high_level.py, pdf2zh/translator.py
https://github.com/Byaidu/PDFMathTranslate/issues/488
=> fix : prompt not work with GUI.

script/setup.bat
https://github.com/Byaidu/PDFMathTranslate/issues/497
=> fix : setup.bat miss setuptools

pyproject.toml
- update yadt requirement to >=0.0.1a20, <0.2.0
=> chore(pyproject): update yadt version requirement

pdf2zh/high_level.py
- introduce re module for regex operations
- extract and process font resource xref using regex
- handle null font entries by setting appropriate keys
=> feat(pdf2zh): Support inserting fonts into indirectly referenced font resources

docs/ADVANCED.md
https://github.com/Byaidu/PDFMathTranslate/issues/487
=> doc(ADVANCED. md): fix openailiked environment variable name

Dockerfile
fix error "ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory"
=> fix(docker): Update Dockerfile to add dependencies

README.md
- include Immersive Translation in acknowledgements
- provide link to contributor rewards details
=> docs(README): add acknowledgement for Immersive Translation

pdf2zh/doclayout.py
=> feat(onnx vcruntime): improve onnx ImportError message

README.md
This pull request includes several updates to the `README.md` file to improve the documentation and provide additional guidance for users. The most important changes are summarized below:
Documentation updates:
* Added a new update entry for February 22, 2025, highlighting better release CI and a well-packaged Windows executable.
* Updated the instructions for using the program without Python installed, changing the section title to "Windows exe" and providing new steps for downloading and running the executable.
* Added a tip for users who cannot access Docker Hub, suggesting they try the image on GitHub Container Registry and providing the necessary commands.
=>  docs: update README.md for improved guidance and additional tips

README.md, docs/ADVANCED.md, pdf2zh/gui.py, pdf2zh/high_level.py, pdf2zh/pdf2zh.py
=> feat: add an option to skip font subsetting

.github/workflows/exe-build.yml, .github/workflows/fork-build.yml, .github/workflows/python-publish.yml, .github/workflows/python-test.yml, Dockerfile, pdf2zh/doclayout.py, pdf2zh/high_level.py, pdf2zh/pdf2zh.py, pdf2zh/translator.py, pyproject.toml, script/_pystand_static.int
This PR introduces a series of improvements to enhance offline asset management and streamline the Windows build/test workflows for the project. The following changes have been made:
- **Support for offline assets**:
- Added functionality to generate, cache, and restore offline assets in the build process.
- Integrated offline asset support into `pdf2zh` using `babeldoc.assets.assets`.
- Added test cases to validate offline translation functionality.
- **Windows Executable Build Workflow**:
- Refactored Python version setup and environment variable handling.
- Integrated caching for dependencies and offline assets metadata.
- Enhanced artifact management, including compression level adjustments.
- Included Visual C++ Redistributable installation in the runtime environment.
- Introduced …
=> feat: enhance offline assets support and improve Windows build/test workflows

README.md, docs/ADVANCED.md, pdf2zh/converter.py, pdf2zh/gui.py, pdf2zh/high_level.py, pdf2zh/pdf2zh.py, pdf2zh/translator.py, test/test_translator.py
=> feat: add option to ignore cache and retranslate

docs/README_zh-CN.md
fix some links in README_zh-CN.md
=> docs(README_zh-CN): fix some links 

pdf2zh/translator.py
fix TKE_REGION missing
https://github.com/Byaidu/PDFMathTranslate/issues/596 https://github.com/Byaidu/PDFMathTranslate/issues/693
=> fix(TMT): :bug: fix TKE_REGION not exist

.github/ISSUE_TEMPLATE/问题反馈_cn.yaml, .github/ISSUE_TEMPLATE/问题反馈_en.yaml
=> update issue templete

pdf2zh/gui.py
因为默认的vfont会不翻译斜体，而且GUI没有方式可以改变这个设置，所以增加了这个选项
=> feat: add vfont in to config

README.md, docs/README_zh-CN.md
I'm making this PR on behalf of Sealos - who have added your app to their app store. Love making open source projects more accessible.
=> Add 1-click deployment on Sealos
