Byaidu/PDFMathTranslate

- pdf2zh/high_level.py
This PR supports automatic device selection supported by pytorch.
- If cuda is properly installed, indicated by `torch.cuda.is_available()`, we use GPU for inference
- *Please note that we have the same outputs of loading the model (`cpu`) yet in inference, GPU is utilized.*
- If not, use `cpu` for compatibility.
- [ckpt = torch.load(file, map_location="cpu") ](https://github.com/Byaidu/PDFMathTranslate/issues/44)
Test passed on RTX3080, using the following environment:
`conda create -n pdf python=3.11 pytorch torchvision transformers ipywidgets ipykernel -y -c nvidia -c conda-forge`
> feat (ai, model): automatically select GPU or CPU

- README.md
- README_zh-CN.md
- pdf2zh/converter.py
- pdf2zh/translator.py
添加腾讯机器翻译接口，读取环境变量中的Tencent_SECRET_ID和Tencent_SECRET_KEY。
添加对应中英文文档说明，修改converter.py添加对应方法入口。
修复了deeplx地址拼接错误以及对于free endpoint的地址判断。
暂未解决的问题：
机器翻译接口对于请求的频率有限制，没对高频请求的情况进行解决。
> 添加腾讯机器翻译接口

- pdf2zh/translator.py
修复了腾讯翻译遇到空字符时的判断，当获取的返回信息不是翻译相关的信息时，全部返回空字符串。
> 修复腾讯翻译遇到空字符报错的问题。

- pdf2zh/doclayout.py
`etag_timeout` default value is 10, it will cause boot lag in Chinese network
> reduce load model time

- pdf2zh/converter.py
Sending blank strings to an LLM will get back "请提供需要翻译的文本", which is highly undesirable.
> Do not send blank strings to translation services.

- README.md
- README_ja-JP.md
- README_zh-CN.md
- pdf2zh/converter.py
- pdf2zh/gui.py
- pdf2zh/translator.py
Further explanation is required for Dify. Three variables, lang_out, lang_in, and text, need to be defined in Dify's workflow input. The text content can be processed through a large model, such as by integrating a knowledge base specific to a particular professional domain, to enhance translation quality.
> Added interfaces for Dify and AnythingLLM to construct a translation process with an integrated knowledge base, improving translation quality.

- README.md
- README_ja-JP.md
- README_zh-CN.md
- pdf2zh/translator.py
There are issues with the translation of the original DeepL API:
Using DeepL's latest API request function, delete the DEEPL_SERVER_URL parameter.
see also https://developers.deepl.com/docs/getting-started/your-first-api-request
> fix the translation api request for DeepL

- pdf2zh/pdfinterp.py
可能与 #206 相关
参考文件 : https://numpy.org/doc/2.2/numpy_2_0_migration_guide.html
由于numpy2 版本后有许多不相容的变化,导致使用mat会丢出例外, 最后pdf可能没被成功处理
以下修改后 #206 提供文件的测试截图
> Fix error when using the `mat` method with NumPy version >= 2.0.0.

- pdf2zh/translator.py
This PR improves the reliability and user experience of the OllamaTranslator by addressing several issues I've encountered.
**Current Issues:**
1. The current implementation sometimes gets stuck generating infinite responses, which can halt the translation process.
2. Additionally, I've observed that certain models perform better than others for specific types of text, but the system currently lacks the ability to leverage multiple models effectively.
**Implemented Solutions:**
To address these issues, I've implemented several key improvements:
1. I've added a length limitation that caps responses at either 2000 characters or three times the input length, whichever is greater. This threshold is based on typical translation length ratios and effectively prevents infinite responses while …
> Enhanced Ollama Response Handling with Retries and Streaming

- pdf2zh/high_level.py
Fixed an issue where certain PDF files would fail with `KeyError: 'china-ss'` due to incorrect font handling during `doc_zh` construction.
I noticed that certain PDF files result in errors. For example:
- https://davidhestenes.net/geocalc/pdf/Tutorial%20on%20Geometric%20Calculus.pdf
The following error occurs:
```text
$ wget https://davidhestenes.net/geocalc/pdf/Tutorial%20on%20Geometric%20Calculus.pdf
$ uv run pdf2zh "Tutorial on Geometric Calculus.pdf"
6%|███▋                                                      | 1/16 [00:00<00:05,  2.64it/s]
Traceback (most recent call last):
File "/home/7shi/repos/PDFMathTranslate/.venv/bin/pdf2zh", line 8, in <module>
sys.exit(main())
File "/home/7shi/repos/PDFMathTranslate/pdf2zh/pdf2zh.py", line 192, in main
translate(**vars(parsed_args))
File …
```
> Fix Font Processing Error

- pdf2zh/converter.py
see https://github.com/Byaidu/PDFMathTranslate/issues/321
> Fix small caps case

- docs/README_GUI.md
- pdf2zh/gui.py
When using the GUI to translate PDFs, I would like to enable the source and target languages to be configured via environment variables.
Thank you in advance!
> Set Translation Languages via Environment Variables in the GUI

- .github/workflows/python-build.yml
> fix: Github action's output path

- Dockerfile
- pdf2zh/converter.py
- pdf2zh/high_level.py
- pyproject.toml
添加更改中日韩字体为思源宋体的选项，以统一 Windows、Linux 和 Mac 系统上的阅读体验。
https://github.com/Byaidu/PDFMathTranslate/issues/271
需要在gradio上的帮助，因为我不太熟悉gradio。
> change CJK fonts to SourceHanSerif

- pdf2zh/converter.py
支持在**行距过大超出原有段落时**，缩小行距。
日本中段落重叠问题尤其严重，因为日语本身较长和片假名的存在导致段落过长。如图在右方段落进行了行距缩小。
> feat: dynamic line space

- pdf2zh/converter.py
When translated into Japanese, the layout tends to break (resulting in overlapping lines), so I think we should adjust the line height.
e.g.
> change japanese lineheight

- .github/workflows/python-build.yml
- .github/workflows/python-publish.yml
- .gitignore
- pdf2zh/pdf2zh.py
- pdf2zh/translator.py
- pyproject.toml
[yadt](https://github.com/funstory-ai/yadt) is a new document translation backend that rewrites pdf2zh's translation backend, not intended for direct end-user use. We hope pdf2zh will be used by users who need self-deployment.
Currently, yadt is still in early development with some serious bugs, but in some cases, it can provide better translation quality than pdf2zh's original backend, and its performance is significantly better.
Breaking Changes:
- Raised minimum Python version required by pdf2zh to 3.12
Known Issues:
- Some formula layout errors
- Loss of all lines (table borders, etc.)
- Some layout parsing errors
- Poor table of contents performance
Major Improvements:
- Introduced intermediate representation, completely decoupling each stage
- Improved performance: Local testing …
> feat(translation): Experimental integration of new YADT backend into CLI

- Dockerfile
- pdf2zh/translator.py
Fix 2 bugs:
1. The OLLAMA_HOST parameter passed by GUI is not set to ollama.Client. As a result, the code will request localhost even if the OLLAMA_HOST is specified by GUI or ENV.
2. Dockerfile will give out: #521  Error. 
I fixed those with minor revisions.
修俩小bug：
1. OLLAMA_HOST这个变量在GUI里以及环境变量里面指定了都没用，因为ollama.Client里面没有传进去
2. Dockerfile构建的docker存在依赖错误，dockerhub里面的docker也有这个问题，已经更新dockerfile
> fix docker and ollama

- pdf2zh/translator.py
1. Improved the prompt to output the translated text only.
2. Removed the CoT output from r1 model.
3. 
Sort of mitigates #545  ,  #535 , but this “Response Too long” infinite loop is not solved and needs more work
1. 修改了一下prompt，让模型直接输出翻译后的文本
2. 把深度求索r1的思维链给过滤了。
算是缓解 #545 , #535 的问题，但是这个Response Too long的死循环的问题没有解决，需要更多的工作
> Minor Bug fix with ollama

- pdf2zh/pdf2zh.py
- pyproject.toml
- import `yadt_init` from `babeldoc.high_level`
- call `yadt_init()` before translation to ensure proper setup
> refactor(pdf2zh): Initialize Babeldoc and replace YADT with Babeldoc

- pdf2zh/pdfinterp.py
The issue in https://github.com/Byaidu/PDFMathTranslate/issues/588 can be fixed through this.
The following files are generated by pdf2zh.
[World.Economic.Outlook_IMF-40-mono.pdf](https://github.com/user-attachments/files/18725344/World.Economic.Outlook_IMF-40-mono.pdf)
[World.Economic.Outlook_IMF-40-dual.pdf](https://github.com/user-attachments/files/18725342/World.Economic.Outlook_IMF-40-dual.pdf)
> fix(pdfinterp): Keep the color space effective after processing xobject.

- pdf2zh/gui.py
Fix typo in service_map key for GorkTranslator
https://github.com/Byaidu/PDFMathTranslate/issues/598
> fix: :pencil2: Fix typo

- pdf2zh/pdf2zh.py
Qwen_mt_Translator was forgotten to be called in yadt_main.
> feat(yadt): integrate Qwen_MT_Translator into yadt_main

- pdf2zh/translator.py
- 将 HTTP 端点地址改为 HTTPS，以提高数据传输的安全性
- 解决原来使用http协议google翻译请求次数多了之后报错的问题
> fix: update API endpoint address in GoogleTranslator class

- pdf2zh/translator.py
- 在 OpenAITranslator 类的 do_translate 方法中添加了对 RateLimitError 的捕获
- 当遇到速率限制错误时，程序将暂停 6 秒后重试一次
- 这种处理方式可以避免因频繁请求导致的接口限制问题，提高程序的稳定性
> fix(pdf2zh): Add error handling for OpenAI API rate limit

- pdf2zh/translator.py
translator.py中GROK的环境变量字段写错了,已经进行更正
> Update the wrong envs name of Grok

- pdf2zh/translator.py
I encountered an authentication error while testing my Azure OpenAI API key.  
After debugging, I found that the `api_version` was hardcoded instead of using the configured environment variable.  
This caused 401 errors like the following:
```
[04/27/25 15:50:37] ERROR ERROR:pdf2zh.converter:Error code: 401 - {'error': {'code': '401', 'message': 'Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.'}}
```
This PR fixes it by properly using the `AZURE_OPENAI_API_VERSION` from the environment settings.
> [Fix] Fix hardcoded Azure OpenAI API version in translator
